// src/App.tsx
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import Home from "./pages/Home";
import About from "./pages/About";
import Contact from "./pages/Contact";
import Page404 from "./pages/404";
import Header from "./layouts/Header";
import Footer from "./layouts/Footer";

function App() {
  return (
    <Router>
      <Header />
      <main className="min-h-screen">
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="*" element={<Page404 />} />
          <Route path="/about" element={<About />} />
          <Route path="/contact" element={<Contact />} />
        </Routes>
      </main>
      <Footer />
    </Router>
  )
}

export default App

// src/App.svelte
<script>
  // @ts-nocheck

  import { Router, Link, Route } from "svelte-routing"
  import Header from "./layouts/Header.svelte"
  import Footer from "./layouts/Footer.svelte"
  import Home from "./pages/Home.svelte"
  import About from "./pages/About.svelte"
  import Contact from "./pages/Contact.svelte"
  import Profile from "./pages/Profile.svelte"
</script>

<Router>
  <Header />
  <main class="min-h-screen py-20">
    <Route path="/" component={Home} />
    <Route path="/about" component={About} />
    <Route path="/contact" component={Contact} />
    <Route path="/profile" component={Profile} />
  </main>
  <Footer />
</Router>

<style>
</style>
